import Header from "@/components/Header";
import Footer from "@/components/Footer";
import DonateButton from "@/components/DonateButton";
import { motion } from "framer-motion";
import {
  Box,
  Container,
  Typography,
  TextField,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Card,
  CardContent,
  InputAdornment,
  Button,
} from "@mui/material";
import { ChevronDown, HelpCircle, Search, Mail } from "lucide-react";
import { useTheme } from "@mui/material/styles";
import { commonStyles, typographyVariants, getGlassStyles } from "@/utils/themeUtils";

const FAQ = () => {
  const theme = useTheme();

  const faqs = [
    {
      question: "What is BasicUtils and what do you offer?",
      answer: "BasicUtils is a comprehensive platform that provides online development tools, educational resources, and insightful blog content. Our mission is to simplify and inspire technology by offering everything developers need in one place."
    },
    {
      question: "Are your tools free to use?",
      answer: "Yes! Most of our tools are completely free to use. We believe in making development resources accessible to everyone. Some advanced features may require a premium account, but our core tools will always remain free."
    },
    {
      question: "Do I need to create an account to use the tools?",
      answer: "No account is required for most of our tools. You can start using them immediately. Creating an account gives you additional benefits like saving your work, accessing premium features, and personalized recommendations."
    },
    {
      question: "How often do you add new tools and content?",
      answer: "We regularly update our platform with new tools and blog content. New tools are typically added monthly, and we publish fresh blog articles weekly. Follow our social media or subscribe to our newsletter to stay updated."
    },
    {
      question: "Can I suggest new tools or features?",
      answer: "Absolutely! We love hearing from our community. You can suggest new tools, features, or improvements through our contact form. We review all suggestions and prioritize based on community interest and impact."
    },
    {
      question: "Is my data safe when using your tools?",
      answer: "Yes, your data privacy and security are our top priorities. We don't store your input data unless explicitly requested (like saving projects). All processing happens client-side when possible, and we use industry-standard security practices."
    },
    {
      question: "Do you offer API access to your tools?",
      answer: "We're currently developing API access for select tools. Premium users will get early access to our APIs. Sign up for our newsletter to be notified when API access becomes available."
    },
    {
      question: "Can I use your tools for commercial projects?",
      answer: "Yes, you can use our tools for both personal and commercial projects. There are no restrictions on the output generated by our tools. However, please respect our terms of service regarding usage limits and proper attribution."
    },
    {
      question: "How can I report bugs or issues?",
      answer: "If you encounter any bugs or issues, please contact us through our support form with detailed information about the problem. Include your browser version, steps to reproduce, and any error messages you see."
    },
    {
      question: "Do you offer technical support?",
      answer: "Yes, we provide technical support through multiple channels. Free users can access our documentation and community forums. Premium users get priority email support with faster response times."
    }
  ];

  return (
    <Box sx={{ minHeight: "100vh", bgcolor: theme.palette.background.default }}>
      <Header />
      <DonateButton />
      <Box component="main" sx={{ pt: 12 }}>
        {/* Hero Section */}
        <Box
          component="section"
          sx={{
            py: 10,
            position: "relative",
            overflow: "hidden",
            "&::before": {
              content: '""',
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              height: "100%",
              background: `radial-gradient(circle, ${theme.palette.primary.main}10 0%, transparent 70%)`,
              opacity: 0.3,
            }
          }}
        >
          <Container maxWidth="lg" sx={{ position: "relative", zIndex: 1 }}>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <Box sx={{ textAlign: "center", maxWidth: "lg", mx: "auto" }}>
                <Box sx={{ display: "flex", justifyContent: "center", mb: 3 }}>
                  <HelpCircle style={{ width: 64, height: 64, color: theme.palette.primary.main }} />
                </Box>
                <Typography
                  variant="h2"
                  component="h1"
                  sx={{
                    ...typographyVariants.sectionTitle,
                    mb: 3,
                    ...commonStyles.textGradient(theme),
                  }}
                >
                  Frequently Asked Questions
                </Typography>
                <Typography
                  variant="h6"
                  sx={{ 
                    color: theme.palette.text.secondary,
                    mb: 4, 
                    lineHeight: 1.6 
                  }}
                >
                  Find answers to common questions about our tools, services, and platform.
                </Typography>
              </Box>
            </motion.div>
          </Container>
        </Box>

        {/* Search Bar */}
        <Box component="section" sx={{ py: 4 }}>
          <Container maxWidth="lg">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <Box sx={{ maxWidth: "md", mx: "auto" }}>
                <TextField
                  fullWidth
                  placeholder="Search questions..."
                  variant="outlined"
                  sx={{
                    "& .MuiOutlinedInput-root": {
                      ...getGlassStyles(theme),
                      borderRadius: theme.shape.borderRadius,
                    },
                  }}
                  InputProps={{
                    startAdornment: (
                      <InputAdornment position="start">
                        <Search style={{ width: 20, height: 20, color: theme.palette.text.secondary }} />
                      </InputAdornment>
                    ),
                  }}
                />
              </Box>
            </motion.div>
          </Container>
        </Box>

        {/* FAQ Accordion */}
        <Box component="section" sx={{ py: 8 }}>
          <Container maxWidth="lg">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <Box sx={{ maxWidth: "md", mx: "auto" }}>
                {faqs.map((faq, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, delay: index * 0.1 }}
                  >
                    <Accordion
                      sx={{
                        mb: 2,
                        ...getGlassStyles(theme),
                        borderRadius: theme.shape.borderRadius,
                        "&:before": {
                          display: "none",
                        },
                        "&:hover": {
                          borderColor: `${theme.palette.primary.main}50`,
                        },
                      }}
                    >
                      <AccordionSummary
                        expandIcon={<ChevronDown style={{ color: theme.palette.primary.main }} />}
                        sx={{
                          "& .MuiAccordionSummary-content": {
                            margin: 0,
                          },
                        }}
                      >
                        <Typography 
                          variant="h6" 
                          fontWeight={600}
                          sx={{ color: theme.palette.text.primary }}
                        >
                          {faq.question}
                        </Typography>
                      </AccordionSummary>
                      <AccordionDetails>
                        <Typography 
                          sx={{ 
                            color: theme.palette.text.secondary, 
                            lineHeight: 1.6 
                          }}
                        >
                          {faq.answer}
                        </Typography>
                      </AccordionDetails>
                    </Accordion>
                  </motion.div>
                ))}
              </Box>
            </motion.div>
          </Container>
        </Box>

        {/* Contact CTA */}
        <Box component="section" sx={{ py: 8 }}>
          <Container maxWidth="lg">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <Card
                sx={{
                  ...getGlassStyles(theme),
                  textAlign: "center",
                  borderRadius: 4,
                  p: 6,
                  maxWidth: "lg",
                  mx: "auto",
                }}
              >
                <Typography 
                  variant="h4" 
                  component="h2" 
                  sx={{ 
                    mb: 2, 
                    fontWeight: "bold",
                    color: theme.palette.text.primary
                  }}
                >
                  Still Have Questions?
                </Typography>
                <Typography 
                  sx={{ 
                    color: theme.palette.text.secondary,
                    mb: 3 
                  }}
                >
                  Can't find what you're looking for? Contact our support team and we'll get back to you as soon as possible.
                </Typography>
                <Button
                  variant="contained"
                  size="large"
                  startIcon={<Mail style={{ width: 20, height: 20 }} />}
                  sx={{
                    ...commonStyles.gradientButton(theme),
                    px: 4,
                  }}
                >
                  Contact Support
                </Button>
              </Card>
            </motion.div>
          </Container>
        </Box>
      </Box>
      <Footer />
    </Box>
  );
};

export default FAQ;